from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.Qt import *

class Ui_MainWindow(object):


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1800, 900)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        self.label_status.setGeometry(QtCore.QRect(1090, 10, 231, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_status.setFont(font)
        self.label_status.setObjectName("label_status")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(1080, 100, 701, 631))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(250, 60, 381, 511))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bar_anger = QtWidgets.QProgressBar(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.bar_anger.setFont(font)
        self.bar_anger.setStyleSheet("QProgressBar::chunk{background-color:rgb(255, 30, 30)} \n"
"QProgressBar{text-align: right}")
        self.bar_anger.setProperty("value", 0)
        self.bar_anger.setObjectName("bar_anger")
        self.verticalLayout.addWidget(self.bar_anger)
        self.bar_disgust = QtWidgets.QProgressBar(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.bar_disgust.setFont(font)
        self.bar_disgust.setStyleSheet("QProgressBar::chunk{background-color:rgb(242, 57, 255)} \n"
"QProgressBar{text-align: right}")
        self.bar_disgust.setProperty("value", 0)
        self.bar_disgust.setObjectName("bar_disgust")
        self.verticalLayout.addWidget(self.bar_disgust)
        self.bar_fear = QtWidgets.QProgressBar(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.bar_fear.setFont(font)
        self.bar_fear.setStyleSheet("QProgressBar::chunk{background-color:rgb(68, 223, 240)} \n"
"QProgressBar{text-align: right}")
        self.bar_fear.setProperty("value", 0)
        self.bar_fear.setObjectName("bar_fear")
        self.verticalLayout.addWidget(self.bar_fear)
        self.bar_happy = QtWidgets.QProgressBar(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.bar_happy.setFont(font)
        self.bar_happy.setStyleSheet("QProgressBar::chunk{background-color:rgb(70, 189, 56)} \n"
"QProgressBar{text-align: right}")
        self.bar_happy.setProperty("value", 0)
        self.bar_happy.setObjectName("bar_happy")
        self.verticalLayout.addWidget(self.bar_happy)
        self.bar_sadness = QtWidgets.QProgressBar(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.bar_sadness.setFont(font)
        self.bar_sadness.setStyleSheet("QProgressBar::chunk{background-color:rgb(239, 207, 88)} \n"
"QProgressBar{text-align: right}")
        self.bar_sadness.setProperty("value", 0)
        self.bar_sadness.setOrientation(QtCore.Qt.Horizontal)
        self.bar_sadness.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.bar_sadness.setObjectName("bar_sadness")
        self.verticalLayout.addWidget(self.bar_sadness)
        self.bar_surprice = QtWidgets.QProgressBar(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.bar_surprice.setFont(font)
        self.bar_surprice.setStyleSheet("QProgressBar::chunk{background-color: rgb(92, 141, 255)}\n"
"QProgressBar{text-align: right}\n"
"")
        self.bar_surprice.setProperty("value", 0)
        self.bar_surprice.setObjectName("bar_surprice")
        self.verticalLayout.addWidget(self.bar_surprice)
        self.bar_neutral = QtWidgets.QProgressBar(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.bar_neutral.setFont(font)
        self.bar_neutral.setStyleSheet("QProgressBar::chunk{background-color:rgb(148, 148, 148)} \n"
"QProgressBar{text-align: right}")
        self.bar_neutral.setProperty("value", 0)
        self.bar_neutral.setObjectName("bar_neutral")
        self.verticalLayout.addWidget(self.bar_neutral)
        self.label_happy = QtWidgets.QLabel(self.groupBox)
        self.label_happy.setGeometry(QtCore.QRect(29, 284, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_happy.setFont(font)
        self.label_happy.setObjectName("label_happy")
        self.label_disgust = QtWidgets.QLabel(self.groupBox)
        self.label_disgust.setGeometry(QtCore.QRect(29, 134, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_disgust.setFont(font)
        self.label_disgust.setObjectName("label_disgust")
        self.label_surprice = QtWidgets.QLabel(self.groupBox)
        self.label_surprice.setGeometry(QtCore.QRect(30, 434, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_surprice.setFont(font)
        self.label_surprice.setObjectName("label_surprice")
        self.label_neutral = QtWidgets.QLabel(self.groupBox)
        self.label_neutral.setGeometry(QtCore.QRect(30, 509, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_neutral.setFont(font)
        self.label_neutral.setObjectName("label_neutral")
        self.label_anger = QtWidgets.QLabel(self.groupBox)
        self.label_anger.setGeometry(QtCore.QRect(30, 59, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_anger.setFont(font)
        self.label_anger.setObjectName("label_anger")
        self.label_fear = QtWidgets.QLabel(self.groupBox)
        self.label_fear.setGeometry(QtCore.QRect(30, 209, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_fear.setFont(font)
        self.label_fear.setObjectName("label_fear")
        self.label_sadness = QtWidgets.QLabel(self.groupBox)
        self.label_sadness.setGeometry(QtCore.QRect(30, 359, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_sadness.setFont(font)
        self.label_sadness.setObjectName("label_sadness")
        self.imgLabel = QtWidgets.QLabel(self.centralwidget)
        self.imgLabel.setGeometry(QtCore.QRect(50, 30, 941, 821))
        self.imgLabel.setObjectName("imgLabel")
        self.imgLabel = QtWidgets.QLabel(self.centralwidget)
        self.imgLabel.setGeometry(QtCore.QRect(50, 30, 941, 821))
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(1310, 13, 341, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(21)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.result.setFont(font)
        self.result.setText("")
        self.result.setObjectName("result")
        self.button_start = QtWidgets.QPushButton(self.centralwidget)
        self.button_start.setGeometry(QtCore.QRect(1440, 760, 300, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.button_start.setFont(font)
        self.button_start.setObjectName("button_start")
        self.button_stop = QtWidgets.QPushButton(self.centralwidget)
        self.button_stop.setGeometry(QtCore.QRect(1100, 760, 300, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.button_stop.setFont(font)
        self.button_stop.setObjectName("button_stop")
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def progress(self, angry):
        self.bar_anger.setValue(angry)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_status.setText(_translate("MainWindow", "Status:"))
        self.groupBox.setTitle(_translate("MainWindow", "emotion status"))
        self.label_happy.setText(_translate("MainWindow", "Happy: "))
        self.label_disgust.setText(_translate("MainWindow", "Disgust:"))
        self.label_surprice.setText(_translate("MainWindow", "Surprice:"))
        self.label_neutral.setText(_translate("MainWindow", "Neutral:"))
        self.label_anger.setText(_translate("MainWindow", "Anger: "))
        self.label_fear.setText(_translate("MainWindow", "Fear:"))
        self.label_sadness.setText(_translate("MainWindow", "Sadness:"))
        self.button_start.setText(_translate("MainWindow", "Start"))
        self.button_stop.setText(_translate("MainWindow", "Stop"))
